import {Icon} from '../components/icon';
import {postImage,coverPosition} from '../lib/blog';
import Link from "next/link";
import { list, publicData, Provider } from "../lib/api";
import { getSiteBrand } from "../lib/server-brand";
import { ProviderCard } from "../components/provider-card";
import { HomeSearch, HomeProviders } from "../components/home-search";
export const dynamic = "force-dynamic";
const routes=["/doctors","/hospitals","/clinics","/laboratories"];
const names=["Doctors","Hospitals","Clinics","Laboratories"];
const icons=["stethoscope","hospital","medicine","lab"];
const specialtyIcon=(name:string)=>/cardio/i.test(name)?'heart':/gynec|women/i.test(name)?'female':/pedia|child/i.test(name)?'baby':/neuro/i.test(name)?'brain':/ortho/i.test(name)?'bone':/\bENT\b|ear/i.test(name)?'ear':/dent/i.test(name)?'tooth':/mental|psych/i.test(name)?'brain':/gastro/i.test(name)?'stomach':/dermat/i.test(name)?'skin':'stethoscope';
const topics=['Fever & Flu','Skin Problems','Stomach Issues','Child Health',"Women’s Health",'Stress & Anxiety','Weight Management','Hair Loss'];
const defaultSpecialties=['General Physician','Dermatology','Pediatrics','Gynecology','Cardiology','Orthopedics','ENT','Neurology','Mental Health','Gastroenterology'];
export default async function Home(){
  const brand=await getSiteBrand();
  const results=await Promise.allSettled([...['doctor','hospital','clinic','lab'].map(kind=>list({kind,limit:'4'})),publicData('care/public/taxonomy'),publicData('content/articles'),publicData('content/faqs'),publicData('care/public/services'),publicData('content/pages')]);
  const get=(i:number):any=>results[i].status==='fulfilled'?results[i].value:null;
  const specialties=get(4)?.specialties||[];
  const specialtyPatterns=[/general|family/i,/dermat/i,/pedia/i,/gynec|obstet/i,/cardio/i,/ortho/i,/\bENT\b|ear nose/i,/neuro(?!endocrin)/i,/mental|psych/i,/gastro/i];
  const specialtyTiles=defaultSpecialties.map((name,i)=>{const match=specialties.find((s:any)=>specialtyPatterns[i].test(s.name));return {name,routeName:match?.name||name,count:match?.count??null}});
  const articles=get(5)?.items||[], faqs=get(6)?.items||[];
  const tests=(get(7)?.items||[]).filter((s:any)=>s.kind==='lab').slice(0,4);
  const conditions=(get(8)?.items||[]).filter((p:any)=>p.data.slug?.startsWith('condition-')).slice(0,8);
  const reviewResults=await Promise.allSettled((get(0)?.items||[]).slice(0,3).map((p:Provider)=>publicData(`care/public/reviews/${p.id}`)));
  const reviews=reviewResults.flatMap((r:any)=>r.status==='fulfilled'?r.value.items||[]:[]).slice(0,1);
  const homeFaqs=faqs.length?faqs.map((f:any)=>f.data):[{question:'How do I book an appointment?',answer:'Open a provider profile, choose a published service and select an available appointment slot.'},{question:'How do I list my business?',answer:'Create a healthcare business account and submit your profile for review.'},{question:'Can I manage my appointments?',answer:'Sign in to your dashboard to view your appointment requests and available actions.'},{question:'Where can I find my care records?',answer:'Your dashboard shows care records that have been shared with your account.'}];
  const heading=(title:string,href:string,label='View All')=><div className="section-head"><h2>{title}</h2><Link className="link" href={href}>{label} →</Link></div>;
  const providers=(i:number)=><div className="grid four">{(get(i)?.items||[]).map((p:Provider)=><ProviderCard key={p.id} provider={p} compact/>)}</div>;
  return <div className="reference-home">
    <section className="home-hero"><div className="container home-hero-grid"><div className="home-hero-copy"><span className="eyebrow"><Icon name="shield" size={14}/> Healthcare Directory in UAE</span><h1>Find the Right Doctor,<br/>Hospital, Clinic or Lab in Dubai</h1><p>Book appointments, find lab tests, read health articles and manage your healthcare needs — in one place.</p><HomeSearch specialties={specialties.map((s:any)=>s.name)}/></div><aside className="home-video card"><h3>Video Consultation</h3><span className="home-video-symbol"><Icon name="video" size={28}/></span><ul className="check-list"><li>Care from wherever you are</li><li>Your consultation records</li><li>Private appointment access</li></ul><p className="muted">Video consultations are not available yet.</p><Link className="button small" href="/video-consultation">Explore Video Care →</Link></aside></div></section>
    <div className="home-stat-strip"><div className="container stats">{names.map((name,i)=><Link href={routes[i]} className="stat" key={name}><span className={`icon-tile ${['','green','purple','orange'][i]}`}><Icon name={icons[i]}/></span><div><strong>{get(i)?.total??'—'}</strong><small>{name}</small></div></Link>)}</div></div>
    <main className="container">
      <section className="home-section">{heading('Browse by Specialties','/specialties','View All Specialties')}<div className="specialty-rail">{specialtyTiles.map((s:any,i:number)=><Link className="specialty-tile" key={s.name} href={`/specialties/${encodeURIComponent(s.routeName)}`}><span className={`icon-tile ${['','orange','purple','green'][i%4]}`}><Icon name={specialtyIcon(s.name)} size={29}/></span><strong>{s.name}</strong>{s.count!==null&&<small>{s.count} providers</small>}</Link>)}</div>{!specialties.length&&<Link className="empty" href="/directory">Explore provider specialties →</Link>}</section>
      <section className="home-section">{heading('Find by Health Concerns','/conditions','View All Conditions')}<div className="concern-rail">{topics.map((title,i)=>{const guide=conditions.find((c:any)=>c.data.title.toLowerCase().includes(title.split(' ')[0].toLowerCase()));return <Link className="concern-card" key={title} href={guide?`/conditions/${guide.data.slug||guide.id}`:`/conditions?q=${encodeURIComponent(title)}`}><span className="concern-photo" role="img" aria-label={title} style={{backgroundPosition:`${(i%4)*100/3}% ${i<4?0:100}%`}}/><strong>{title}</strong></Link>})}</div></section>
      <HomeProviders groups={names.map((label,i)=>({label,href:routes[i],items:get(i)?.items||[],available:!!get(i)}))}/>
      <section className="home-section home-hospitals">{heading('Top Hospitals in Dubai','/hospitals','View All Hospitals')}{providers(1)}{!get(1)?.items?.length&&<div className="empty">{get(1)?'No published hospitals yet.':'Hospital listings temporarily unavailable.'}</div>}</section>
      <div className="home-clinic-tests"><section className="home-section">{heading('Top Clinics in Dubai','/clinics','View All Clinics')}{providers(2)}{!get(2)?.items?.length&&<div className="empty">{get(2)?'No published clinics yet.':'Clinic listings temporarily unavailable.'}</div>}</section><section className="home-section">{heading('Popular Lab Tests in Dubai','/lab-tests','View All Tests')}<div className="card test-list">{tests.map((s:any)=><div className="test-row" key={s.id}><span className="icon-tile"><Icon name="lab" size={18}/></span><Link href={`/lab-tests/${s.id}`}>{s.name}</Link><strong>AED {(s.price_minor/100).toFixed(0)}</strong><Link className="button small" href={`/book/${s.slug}`}>Book</Link></div>)}{!tests.length&&<p className="muted">{get(7)?'Published tests will appear here.':'Test catalog temporarily unavailable.'}</p>}</div></section></div>
      <section className="home-process card"><h2>How It Works</h2><p className="muted">Get healthcare in 4 simple steps</p><div className="steps-grid">{[['search','Search','Find doctors, hospitals, clinics or tests.'],['calendar','Book','Choose an available date and time.'],['video','Consult','Visit your chosen care provider.'],['file','Get Care','Access shared reports and follow-up.']].map(([icon,title,text],i)=><div key={title}><span className="icon-tile"><Icon name={icon} size={30}/></span><h3>{i+1}. {title}</h3><p>{text}</p></div>)}</div></section>
      <section className="home-about grid two"><article className="card home-about-intro"><h2>Who We Are & What We Do</h2><h3>Your Healthcare Directory in Dubai</h3><p>Find healthcare providers, compare their services and request appointments. {brand} brings your bookings and shared care records together in one place.</p><Link className="button secondary small" href="/directory">Explore Healthcare →</Link></article><article className="card home-about-benefits"><h2>Why {brand} is Helpful</h2><ul className="check-list"><li>Find doctors, hospitals, clinics and laboratories</li><li>Compare published services and prices</li><li>Request available appointment slots</li><li>Keep your shared care records together</li></ul><Link className="link" href="/dashboard">Open your personal dashboard →</Link></article></section>
      <section className="home-section">{heading(`List Your Business on ${brand}`,'/list-your-business','Learn More')}<p className="muted">Build your healthcare profile and connect with patients.</p><div className="home-business-grid">{['Doctor','Hospital','Clinic','Lab'].map((name,i)=><article className={`business-tile tone-${i}`} key={name}><h3><span className="icon-tile"><Icon name={icons[i]}/></span>I'm a {name}{i===1||i===2?' Owner':''}</h3><ul className="check-list"><li>Create your profile</li><li>Showcase services and prices</li><li>Manage appointment requests</li><li>Keep your details up to date</li></ul><Link className="button small" href={`/auth?mode=register&role=${name.toLowerCase()}`}>List Your {name} →</Link></article>)}<aside className="card"><h3>Why List with Us?</h3><ul className="check-list"><li>Help patients discover your business</li><li>Manage your published information</li><li>Organize bookings and services</li></ul><Link className="button small" href="/list-your-business">Explore Business Listings →</Link></aside></div></section>
      <section className="home-section"><h2>All-in-One Platform for Healthcare Providers</h2><div className="home-feature-rail">{[['user','Profile Management','Update your details anytime','/dashboard'],['calendar','Appointment Management','Manage your appointment requests','/dashboard'],['people','Patient Management','Access shared care records','/dashboard'],['star','Reviews & Ratings','Read patient feedback','/doctors'],['file','Blog Posts','Share articles and health tips','/dashboard?tab=posts&new=1'],['card','Invoices & Payments','Track your care invoices','/dashboard']].map(([icon,title,text,href])=><Link href={href} key={title}><span className="icon-tile"><Icon name={icon}/></span><div><strong>{title}</strong><p>{text}</p></div></Link>)}</div></section>
      <section className="home-section">{heading('Latest Health Articles','/blog','View All Articles')}<div className="grid four">{articles.slice(0,4).map((a:any)=><Link className="card home-article" href={`/blog/${a.data.slug||a.id}`} key={a.id}>{postImage(a)&&<img src={postImage(a)} alt={a.data.imageAlt||""} style={{objectPosition:coverPosition(a)}}/>}<div><h3>{a.data.title}</h3><small>{a.data.category||'Health'} · {a.data.author}</small></div></Link>)}</div>{!articles.length&&<div className="empty">{get(5)?'Health articles will appear when published.':'Articles temporarily unavailable.'}</div>}</section>
      <section className="home-section home-bottom-grid"><div className="home-listing-options"><h2>Business Listing Options</h2><p className="muted">Build and manage your healthcare presence.</p><div className="home-listing-cards">{[['user','Doctor Profile','Show your expertise and care services','doctor'],['hospital','Hospital or Clinic','Introduce your facility and services','hospital'],['lab','Lab & Diagnostics','Publish your tests and booking options','lab']].map(([icon,title,text,role])=><article className="card" key={title}><span className="icon-tile"><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p><ul className="check-list"><li>Published business profile</li><li>Services and contact details</li><li>Appointment management</li></ul><Link className="button secondary small" href={`/auth?mode=register&role=${role}`}>Get Started →</Link></article>)}</div><Link className="link" href="/list-your-business">Explore listing packages →</Link></div><div className="card home-faq"><h2>Frequently Asked Questions</h2>{homeFaqs.map((f:any,i:number)=><details className="detail-item" key={i}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div><div className="card home-patient-reviews"><h2>What Our Patients Say</h2>{reviews.length?reviews.map((r:any)=><blockquote key={r.id}><Icon name="quote" size={25}/><p>“{r.comment}”</p><span className="review-stars" aria-label={`${r.rating} out of 5 stars`}>{'★'.repeat(r.rating)}</span><strong>{r.patient_name}</strong></blockquote>):<div className="home-review-empty"><span className="icon-tile"><Icon name="star" size={28}/></span><h3>Make an informed choice</h3><p>Read published patient reviews on provider profiles.</p><Link className="link" href="/doctors">Explore Doctors →</Link></div>}</div></section>

    </main>
  </div>;
}

