"use client";
import {useEffect,useState} from 'react';
import {Icon} from "./icon";
import {api,formatMoney,localTime} from '../lib/client-api';
type Row=Record<string,any>;
const colors=['#0877ff','#42bbff','#fc5287','#ffab3d','#825de7'];
function Panel({title,children,onView,className=''}:{title:string;children:React.ReactNode;onView?:()=>void;className?:string}){return <section className={`card admin-panel ${className}`}><div className="card-head"><h3>{title}</h3>{onView&&<button className="link" onClick={onView}>View All</button>}</div>{children}</section>}
function Empty(){return <div className="admin-empty">No records in this period</div>}
function Table({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return rows.length?<div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>:<Empty/>}
function Status({value}:{value:string}){return <span className={`badge ${['Pending','Requested','Draft','Issued'].includes(value)?'pending':['Cancelled','Rejected'].includes(value)?'cancelled':''}`}>{value}</span>}
export function AdminOverview({overview,appointments,from,to,refresh,onTab,onListing,onPost}:{overview:any;appointments:Row[];from:string;to:string;refresh:unknown;onTab:(tab:string)=>void;onListing:(kind:string)=>void;onPost:()=>void}){
 const [insights,setInsights]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;setInsights(null);setError('');api('care/admin-insights?'+new URLSearchParams({from,to})).then(r=>{if(active)setInsights(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[from,to,refresh]);
 const counts=overview?.listingKinds||[], total=counts.reduce((n:number,r:Row)=>n+r.count,0);
 const bookings=overview?.bookings||[], booked=bookings.reduce((n:number,r:Row)=>n+r.count,0);
 const posts=insights?.posts?.reduce((n:number,r:Row)=>n+r.count,0);
 const revenue=insights?.revenueTrend||[], paid=revenue.reduce((n:number,r:Row)=>n+r.amount,0);
 const daily=insights?.bookingTrend||[], dates=[...new Set<string>(daily.map((r:Row)=>r.date))];
 const maxBooking=Math.max(1,...dates.map(d=>daily.filter((r:Row)=>r.date===d).reduce((n:number,r:Row)=>n+r.count,0)));
 let offset=0;const gradient=counts.map((r:Row,i:number)=>{const start=offset;offset+=r.count/(total||1)*100;return `${colors[i%colors.length]} ${start}% ${offset}%`}).join(',');
 const maxRevenue=Math.max(1,...revenue.map((r:Row)=>r.amount));
 const points=revenue.map((r:Row,i:number)=>`${35+i*425/Math.max(1,revenue.length-1)},${155-r.amount/maxRevenue*125}`).join(' ');
 const rank=(items:Row[])=>items.length?<div className="ranking">{items.map((r,i)=><div key={r.id||r.name}><span className="rank-avatar">{r.name.slice(0,1)}</span><div><strong>{r.name}</strong>{r.specialty&&<small>{r.specialty}</small>}</div><b>{r.count}</b><span className="rank-track"><i style={{width:`${r.count/Math.max(1,items[0].count)*100}%`}}/></span></div>)}</div>:<Empty/>;
 return <div className="admin-overview">
 {error&&<div className="error" role="alert">Dashboard insights unavailable: {error}</div>}
 <div className="metric-grid">{[['♙',overview?total:'—','Total Listings',counts.map((r:Row)=>`${r.count} ${r.kind}`).join('  |  ')],['▦',overview?booked:'—','Total Bookings',bookings.map((r:Row)=>`${r.count} ${r.status}`).join('  |  ')],['▣',insights?formatMoney(paid):'—','Total Payments','Received payments · selected payment dates'],['▤',posts??'—','Blog Posts',insights?.posts?.map((r:Row)=>`${r.count} ${r.status||'Unspecified'}`).join('  |  ')]].map(([icon,value,label,detail],i)=><div className="card admin-metric" key={label}><span className={`metric-icon color-${i}`}><Icon name={['user','calendar','card','file'][i]} size={32}/></span><div><strong>{value}</strong><p>{label}</p></div><small>{detail||'No records yet'}</small></div>)}</div>
 <div className="admin-charts">
 <Panel title="Bookings Overview"><div className="chart-key">{['Confirmed','Requested','Cancelled'].map((s,i)=><span key={s}><i style={{background:colors[i]}}/>{s}</span>)}</div>{dates.length?<div className="daily-chart" role="img" aria-label="Daily bookings by status"><div className="daily-grid"><span>{maxBooking}</span><span>{Math.round(maxBooking/2)}</span><span>0</span></div><div className="daily-bars">{dates.map(d=><div key={d} title={`${d}: ${daily.filter((r:Row)=>r.date===d).reduce((n:number,r:Row)=>n+r.count,0)} bookings`}>{['Cancelled','Requested','Confirmed','Completed','Rejected'].map((s,i)=>{const n=daily.find((r:Row)=>r.date===d&&r.status===s)?.count||0;return <span key={s} style={{height:`${n/maxBooking*135}px`,background:[colors[2],colors[1],colors[0],'#00b883','#9da8bd'][i]}}/>})}<small>{d.slice(5)}</small></div>)}</div></div>:<Empty/>}</Panel>
 <Panel title="Revenue Overview (AED)">{revenue.length?<svg className="revenue-chart" viewBox="0 0 480 190" role="img" aria-label={`Received revenue ${formatMoney(paid)}`}><defs><linearGradient id="revenue-fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#00b65d" stopOpacity=".3"/><stop offset="1" stopColor="#00b65d" stopOpacity=".03"/></linearGradient></defs>{[30,92,155].map((y,i)=><g key={y}><line x1="35" x2="460" y1={y} y2={y} stroke="#e5edf6"/><text x="0" y={y+4} fontSize="10" fill="#64718c">{Math.round(maxRevenue/100*(1-i/2))}</text></g>)}<polygon points={`35,155 ${points} ${35+(revenue.length-1)*425/Math.max(1,revenue.length-1)},155`} fill="url(#revenue-fill)"/><polyline points={points} stroke="#00af60" strokeWidth="2.5" fill="none"/>{revenue.map((r:Row,i:number)=><circle key={r.date} cx={35+i*425/Math.max(1,revenue.length-1)} cy={155-r.amount/maxRevenue*125} r="3" fill="#00af60"><title>{r.date}: {formatMoney(r.amount)}</title></circle>)}<text x="35" y="180" fontSize="10">{revenue[0].date}</text><text x="460" y="180" fontSize="10" textAnchor="end">{revenue.at(-1).date}</text></svg>:<Empty/>}</Panel>
 <Panel title="Listings by Type"><div className="listing-donut"><div className="donut" style={{background:gradient?`conic-gradient(${gradient})`:'#e7eff8'}}><strong>{overview?total:'—'}<small>Total Listings</small></strong></div><div>{counts.map((r:Row,i:number)=><div className="legend" key={r.kind}><span><i style={{background:colors[i%colors.length]}}/>{r.kind}</span><strong>{r.count}</strong></div>)}</div></div></Panel>
 </div>
 <div className="admin-content-grid"><div className="admin-primary">
 <div className="admin-tables"><Panel title="Recent Bookings" onView={()=>onTab('appointments')}><Table heads={['Reference','Patient','Provider','Date & Time','Status']} rows={appointments.slice(0,5).map(a=>[a.id.slice(0,8),a.patient_name,a.provider_name,localTime(a.starts_at),<Status value={a.status}/>])}/></Panel><Panel title="Recent Payments" onView={()=>onTab('invoices')}><Table heads={['Reference','Amount','Method','Status']} rows={(insights?.payments||[]).map((p:Row)=>[p.id.slice(0,8),formatMoney(p.amount_minor),p.payment_method||'Not supplied',<Status value={p.status}/>])}/></Panel></div>
 <div className="admin-lower"><Panel title="Top Doctors by Bookings" onView={()=>onTab('appointments')}>{rank(insights?.doctors||[])}</Panel><Panel title="Top Locations">{rank(insights?.locations||[])}</Panel><Panel title="Recent Blog Posts" onView={()=>onTab('cms:articles')}><Table heads={['Title','Category','Status']} rows={(insights?.recentPosts||[]).map((p:Row)=>[p.data.title,p.data.category||'—',<Status value={p.data.status||'Draft'}/>])}/></Panel></div>
 </div><aside className="admin-right"><Panel title="Quick Actions"><div className="quick-grid">{[['♙','Add Doctor',()=>onListing('doctor')],['▥','Add Clinic',()=>onListing('clinic')],['▥','Add Hospital',()=>onListing('hospital')],['⚗','Add Lab',()=>onListing('lab')],['▦','View Bookings',()=>onTab('appointments')],['▤','Add Blog Post',onPost]].map(([icon,label,fn])=><button key={String(label)} onClick={fn as ()=>void}><span>{icon as string}</span>{label as string}</button>)}</div></Panel><Panel title="System Status"><div className="system-status"><p><span>Directory API</span><strong>{insights?'Connected':error?'Unavailable':'Checking'}</strong></p><p><span>Appointments</span><strong>{overview?'Connected':'Checking'}</strong></p><p><span>Online payments</span><small>Not configured</small></p><p><span>Video consultations</span><small>Not configured</small></p><p><span>Email delivery</span><small>Not verified</small></p></div></Panel></aside></div>
 </div>
}
