"use client";

import Link from 'next/link';
import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { Icon } from './icon';

// Visual fixtures are deliberately local. Nothing here seeds the production database.
const image = '/images/home-reference-assets.png';
function rotated<T>(items:T[],offset:number):T[]{const n=((offset%items.length)+items.length)%items.length;return [...items.slice(n),...items.slice(0,n)]}
type Crop = [number, number, number, number];
function Photo({crop, className='', label=''}:{crop:Crop;className?:string;label?:string}) {
  const [x,y,w,h]=crop;
  const style:CSSProperties={backgroundImage:`url('${image}')`,backgroundSize:`${823/w*100}% ${1912/h*100}%`,backgroundPosition:`${x/(823-w)*100}% ${y/(1912-h)*100}%`};
  return <span className={`rh-photo ${className}`} style={style} role={label?'img':undefined} aria-label={label||undefined} aria-hidden={label?undefined:true}/>;
}
const specialties=[['General Physician','stethoscope'],['Dermatology','skin'],['Pediatrics','baby'],['Gynecology','female'],['Cardiology','heart'],['Orthopedics','bone'],['ENT','ear'],['Neurology','brain'],['Mental Health','brain'],['Gastroenterology','stomach']];
const specialtyCenters=[72,153,229,302,376,450,523,596,670,748];
const statX=[39,167,295,413,562,708];
const concerns=['Fever & Flu','Skin Problems','Stomach Issues','Child Health',"Women’s Health",'Stress & Anxiety','Weight Management','Hair Loss'];
const doctors=[
  {name:'Dr. Sarah Khan',specialty:'Cardiologist',place:'MedCare Clinic, Dubai',rating:'4.9',reviews:120,day:'Today',crop:[43,588,51,61] as Crop},
  {name:'Dr. Ahmed Raza',specialty:'Dermatologist',place:'City Health Center, Dubai',rating:'4.8',reviews:210,day:'Today',crop:[235,588,52,61] as Crop},
  {name:'Dr. Fatima Noor',specialty:'Pediatrician',place:'LifeCare Clinic, Sharjah',rating:'4.9',reviews:178,day:'Tomorrow',crop:[428,588,52,61] as Crop},
  {name:'Dr. Bilal Sheikh',specialty:'Orthopedic Surgeon',place:'MedCity Hospital, Dubai',rating:'4.7',reviews:165,day:'Today',crop:[623,588,52,61] as Crop},
];
const hospitals=[['MedCare Hospital','Al Barsha, Dubai','4.8','320'],['City Health Center','Downtown, Dubai','4.7','310'],['LifeCare Hospital','JLT, Dubai','4.6','280'],['Emirates Specialist Hospital','Deira, Dubai','4.5','210']];
const clinics=[['MedCare Clinic','Business Bay','4.8','420'],['Wellness Clinic','Jumeirah','4.7','310'],['Prime Care Clinic','Al Karama','4.6','280'],['HealthPlus Clinic','Discovery Gardens','4.6','260']];
const articles=[['10 Tips for a Stronger Immune System','Lifestyle',[39,1583,72,53]],['How to Manage Stress in Daily Life','Mental Health',[234,1583,65,53]],['Understanding Diabetes: Symptoms and Treatment','Diabetes',[434,1583,65,53]],['Skin Care Tips for Healthy and Glowing Skin','Dermatology',[615,1583,66,53]]] as const;
const questions=[['How do I book an appointment?','Choose a doctor and an available appointment time. This homepage is a visual demo; use the live directory to make an actual booking.'],['Is the video consultation secure?','The video consultation card is sample content for this design preview. A live video service is not connected.'],['Can I get a prescription online?','Prescription availability depends on your actual care provider. No prescription service is provided by this demo.'],['How do I list my business?','Create a healthcare business account and submit your profile for review.'],['What payment methods are accepted?','The prices and packages shown here are dummy examples. No payment is collected in this preview.'],['Can I reschedule or cancel?','Sign in to your existing dashboard to manage real appointment requests.'],['Is MedCare available outside Dubai?','This reference homepage uses sample MedCare content. Browse the live directory to see actual locations.']];
const business=[
  ['stethoscope',"I’m a Doctor",['Create your profile','Showcase your expertise','Get more patients','Manage appointments'],'List Your Profile','doctor'],
  ['hospital',"I’m a Hospital Owner",['List your hospital','Show facilities & departments','Manage doctors and services','Get online appointments'],'List Your Hospital','hospital'],
  ['medicine',"I’m a Clinic Owner",['List your clinic','Show services & doctors','Receive more patients','Manage bookings & reviews'],'List Your Clinic','clinic'],
  ['lab',"I’m a Lab / Technician",['List your lab or diagnostic center','Add tests & prices','Receive online bookings','Share reports with patients'],'List Your Lab','lab'],
] as const;

function CheckList({items}:{items:readonly string[]}) {return <ul className="rh-checks">{items.map(t=><li key={t}><Icon name="check" size={10}/><span>{t}</span></li>)}</ul>}
function SectionTitle({children,href,label='View All'}:{children:ReactNode;href:string;label?:string}) {return <div className="rh-section-title"><h2>{children}</h2><Link href={href}>{label} →</Link></div>}
function Arrow({direction,onClick,label}:{direction:'left'|'right';onClick:()=>void;label:string}) {return <button className={`rh-arrow rh-arrow-${direction}`} aria-label={label} onClick={onClick}><Icon name="chevron" size={13}/></button>}

export function ReferenceHome(){
  const root=useRef<HTMLDivElement>(null);
  const [kind,setKind]=useState('doctor'),[query,setQuery]=useState(''),[location,setLocation]=useState('Dubai'),[date,setDate]=useState('');
  const [offsets,setOffsets]=useState({specialties:0,providers:0,hospitals:0,clinics:0});
  const [group,setGroup]=useState(0),[planRole,setPlanRole]=useState('Doctor'),[favorites,setFavorites]=useState<string[]>([]),[menu,setMenu]=useState(false);
  const [dialog,setDialog]=useState<{title:string;body:string}|null>(null);
  const specialtyRail=useRef<HTMLDivElement>(null),concernRail=useRef<HTMLDivElement>(null),doctorRail=useRef<HTMLDivElement>(null),hospitalRail=useRef<HTMLDivElement>(null),clinicRail=useRef<HTMLDivElement>(null);
  const closeButton=useRef<HTMLButtonElement>(null),previousFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{const node=root.current;if(!node)return;const resize=new ResizeObserver(()=>node.style.setProperty('--rh-u',`${node.clientWidth<=600?1:Math.min(node.clientWidth/823,1.7)}px`));resize.observe(node);return()=>resize.disconnect()},[]);
  useEffect(()=>{if(!dialog)return;previousFocus.current=document.activeElement as HTMLElement;closeButton.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setDialog(null);if(e.key==='Tab'){const controls=Array.from(document.querySelectorAll<HTMLElement>('.rh-dialog button,.rh-dialog a'));if(e.shiftKey&&document.activeElement===controls[0]){e.preventDefault();controls.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===controls.at(-1)){e.preventDefault();controls[0]?.focus()}}};document.addEventListener('keydown',onKey);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',onKey);previousFocus.current?.focus()}},[dialog]);
  const sample=(title:string,body='This is a sample listing in the reference design. Browse the live directory to view real providers and available appointments.')=>setDialog({title,body});
  const scroll=(ref:{current:HTMLDivElement|null},direction:number)=>{const el=ref.current;if(!el)return;if(el.scrollWidth>el.clientWidth+1){el.scrollBy({left:direction*250,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});return}const key=ref===specialtyRail?'specialties':ref===doctorRail?'providers':ref===hospitalRail?'hospitals':'clinics';setOffsets(prev=>({...prev,[key]:prev[key]+direction}))};
  const toggleFavorite=(name:string)=>setFavorites(prev=>prev.includes(name)?prev.filter(n=>n!==name):[...prev,name]);
  const facilityCards=(items:string[][],type:'hospital'|'clinic')=>items.map(([name,area,rating,reviews],i)=><article className={`rh-facility rh-${type}-card`} key={name}><Photo className="rh-building" crop={type==='hospital'?[34+hospitals.findIndex(([n])=>n===name)*193,739,62,69]:[35+clinics.findIndex(([n])=>n===name)*131,861,36,58]} label={`${name} sample building`}/><div><h3>{name}</h3><p>{area}</p><span className="rh-rating"><b>★ ★</b> {rating} <small>({reviews} reviews)</small></span>{type==='hospital'&&<button className="rh-outline" onClick={()=>sample(name)}>♧ Book Appointment</button>}</div>{type==='clinic'&&<button className="rh-primary" onClick={()=>sample(name)}>Book Appointment</button>}</article>);

  return <div className="rh-page" ref={root}>
    <header className="rh-header"><div className="rh-wrap rh-nav"><Link className="rh-brand" href="/" aria-label="MedCare homepage"><span><Photo crop={[29,5,27,25]}/></span><div><strong>MedCare</strong><small>Find Doctor. Book Care. Live Healthy.</small></div></Link><button className="rh-mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} aria-controls="rh-navigation" onClick={()=>setMenu(!menu)}><Icon name="menu" size={19}/></button><nav id="rh-navigation" className={menu?'rh-menu-open':''}>{[['Find Doctors','/doctors'],['Hospitals','/hospitals'],['Clinics','/clinics'],['Lab Tests','/lab-tests'],['Health Articles','/blog'],['For Patients','/dashboard'],['For Businesses','/list-your-business']].map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><div className="rh-nav-actions"><button className="rh-country" onClick={()=>sample('UAE directory','This sample homepage is set to the UAE. The live directory currently lists providers in Dubai.')}><span className="rh-flag"/> UAE <span>⌄</span></button><button className="rh-header-search" aria-label="Focus provider search" onClick={()=>document.getElementById('rh-specialty')?.focus()}><Icon name="search" size={15}/></button><Link className="rh-login" href="/auth">Login</Link><Link className="rh-primary" href="/auth?mode=register">Sign Up</Link></div></div></header>
    <section className="rh-hero"><div className="rh-wrap rh-hero-inner"><div className="rh-hero-copy"><span className="rh-eyebrow"><Icon name="shield" size={9}/> #1 Healthcare Directory in UAE</span><h1>Find the Right Doctor,<br/>Hospital, Clinic or Lab in Dubai</h1><p>Book appointments, get instant video consultation, find lab tests, read trusted health<br className="rh-desktop-break"/> articles and manage all your healthcare needs — in one place, faster.</p></div><Photo className="rh-hero-doctor" crop={[498,48,125,230]} label="Doctor illustration from the reference design"/>
    <div className="rh-search"><div className="rh-search-tabs">{[['doctor','Find Doctor','stethoscope'],['hospital','Find Hospital','hospital'],['clinic','Find Clinic','medicine'],['lab','Find Lab Test','lab'],['video','Video Consult','video']].map(([id,label,icon])=><button type="button" className={kind===id?'active':''} aria-pressed={kind===id} key={id} onClick={()=>setKind(id)}><Icon name={icon} size={10}/>{label}</button>)}</div><form onSubmit={e=>{e.preventDefault();sample(`Search ${kind==='lab'?'lab tests':kind==='video'?'video care':kind+'s'}${query?': '+query:''}`,`Sample search in ${location||'Dubai'}${date?' on '+date:''}. Use the live directory to see real results and available appointments.`)}}><div className="rh-field-captions" aria-hidden="true"><span>Specialty</span><span>Location</span><span>Date</span><span/></div><div className="rh-search-fields"><select id="rh-specialty" aria-label="Specialty" value={query} onChange={e=>setQuery(e.target.value)}><option value="">e.g Dermatologist</option>{specialties.map(([name])=><option key={name}>{name}</option>)}</select><input aria-label="Location" placeholder="Location" value={location} onChange={e=>setLocation(e.target.value)}/><div className="rh-date"><input type={date?'date':'text'} aria-label="Appointment date" placeholder="Any Date" value={date} onFocus={e=>e.currentTarget.type='date'} onBlur={e=>{if(!e.currentTarget.value)e.currentTarget.type='text'}} onChange={e=>setDate(e.target.value)}/><Icon name="calendar" size={11}/></div><button className="rh-primary" type="submit">Search Now</button></div></form><div className="rh-popular"><b>Popular Searches:</b>{['Cardiologist','Dermatology','Pediatrician','Gynecologist','ENT','General Physician','Orthopedic'].map(name=><button key={name} onClick={()=>{const match=specialties.find(([s])=>s.toLowerCase().slice(0,6)===name.toLowerCase().slice(0,6));setQuery(match?.[0]||name)}}>{name}</button>)}</div></div>
    <aside className="rh-video"><h2>Instant Video Consultation</h2><ul>{[['shield','Talk to a doctor from anywhere'],['file','Get prescription online'],['shield','Secure and private'],['clock','Available 24/7']].map(([icon,text])=><li key={text}><Icon name={icon} size={13}/>{text}</li>)}</ul><button className="rh-primary" onClick={()=>sample('Video consultation preview','This is a sample video consultation card. No live consultation is started or charged.')}><Icon name="video" size={12}/> Start Video Consultation</button><div className="rh-online"><div>{doctors.slice(0,3).map(d=><Photo crop={d.crop} key={d.name}/>)}</div><span>500+ Doctors Online</span></div></aside></div></section>
    <section className="rh-statistics"><div className="rh-wrap">{[['stethoscope','5,000+','Doctors'],['hospital','1,200+','Hospitals'],['medicine','2,500+','Clinics'],['lab','800+','Labs & Diagnostic Centers'],['people','500,000+','Patients Every Month'],['star','4.8/5','Average Rating']].map(([icon,count,label],i)=><div className={`rh-stat rh-tone-${i}`} key={label}><span className="rh-icon"><Photo crop={[statX[i],289,33,32]}/></span><div><strong>{count}</strong><small>{label}</small></div></div>)}</div></section>
    <main className="rh-wrap rh-main">
      <section className="rh-specialties"><SectionTitle href="/specialties" label="View All Specialties">Browse by Specialties</SectionTitle><div className="rh-rail-wrap"><Arrow direction="left" label="Previous specialties" onClick={()=>scroll(specialtyRail,-1)}/><div className="rh-specialty-rail" ref={specialtyRail}>{rotated(specialties,offsets.specialties).map(([name,icon],i)=><button className={`rh-specialty rh-tone-${i%6}`} key={name} onClick={()=>sample(name,`Explore ${name.toLowerCase()} providers in the live directory. This tile belongs to the sample design.`)}><span className="rh-icon"><Photo crop={[specialtyCenters[specialties.findIndex(([n])=>n===name)]-18,370,36,36]}/></span><strong>{name}</strong></button>)}</div><Arrow direction="right" label="Next specialties" onClick={()=>scroll(specialtyRail,1)}/></div></section>
      <section className="rh-concerns"><SectionTitle href="/conditions" label="View All Conditions">Find by Health Concerns</SectionTitle><div className="rh-concern-rail" ref={concernRail}>{concerns.map((name,i)=><button key={name} onClick={()=>sample(name,'This is a sample health-concern tile. Visit the published health guides for maintained information.')}><Photo crop={[29+i*97,455,82,62]} label={name}/><strong>{name}</strong></button>)}</div></section>
      <section className="rh-providers"><div className="rh-section-title"><div className="rh-provider-tabs">{['Top Rated Doctors','Top Hospitals','Top Clinics','Top Labs'].map((name,i)=><button className={group===i?'active':''} aria-pressed={group===i} key={name} onClick={()=>setGroup(i)}>{name}</button>)}</div><Link href={['/doctors','/hospitals','/clinics','/laboratories'][group]}>View All {['Doctors','Hospitals','Clinics','Labs'][group]} →</Link></div><div className="rh-rail-wrap"><Arrow direction="left" label="Previous providers" onClick={()=>scroll(doctorRail,-1)}/><div className="rh-doctor-rail" ref={doctorRail}>{group===0?rotated(doctors,offsets.providers).map(d=><article className="rh-doctor-card" key={d.name}><Photo className="rh-portrait" crop={d.crop} label={`${d.name} sample portrait`}/><div className="rh-doctor-info"><h3>{d.name}</h3><p>{d.specialty}</p><span className="rh-rating"><b>★ ★</b> {d.rating} <small>({d.reviews} reviews)</small></span><p className="rh-place"><Icon name="hospital" size={9}/> {d.place}</p><span className={`rh-availability ${d.day==='Tomorrow'?'tomorrow':''}`}><Icon name="check" size={9}/> Available {d.day}</span></div><button className="rh-favorite" aria-label={`Favorite ${d.name}`} aria-pressed={favorites.includes(d.name)} onClick={()=>toggleFavorite(d.name)}>{favorites.includes(d.name)?'♥':'♡'}</button><button className="rh-primary" onClick={()=>sample('Book '+d.name)}>Book Appointment</button></article>):group===1?facilityCards(rotated(hospitals,offsets.providers),'hospital'):group===2?facilityCards(rotated(clinics,offsets.providers),'clinic'):[['MedCare Diagnostics','Al Barsha'],['City Health Lab','Downtown'],['LifeCare Laboratory','JLT'],['Emirates Diagnostics','Deira']].map(([name,area],i)=><article className="rh-doctor-card rh-lab-demo" key={name}><span className="rh-icon"><Icon name="lab" size={29}/></span><h3>{name}</h3><p>{area}, Dubai</p><p className="rh-rating"><b>★ ★</b> 4.8 <small>(120 reviews)</small></p><button className="rh-primary" onClick={()=>sample(name)}>View Lab Tests</button></article>)}</div><Arrow direction="right" label="Next providers" onClick={()=>scroll(doctorRail,1)}/></div></section>
      <section className="rh-hospitals"><SectionTitle href="/hospitals" label="View All Hospitals">Top Hospitals in Dubai</SectionTitle><div className="rh-rail-wrap"><Arrow direction="left" label="Previous hospitals" onClick={()=>scroll(hospitalRail,-1)}/><div className="rh-hospital-rail" ref={hospitalRail}>{facilityCards(rotated(hospitals,offsets.hospitals),'hospital')}</div><Arrow direction="right" label="Next hospitals" onClick={()=>scroll(hospitalRail,1)}/></div></section>
      <div className="rh-clinics-tests"><section><SectionTitle href="/clinics" label="View All Clinics">Top Clinics in Dubai</SectionTitle><div className="rh-rail-wrap"><Arrow direction="left" label="Previous clinics" onClick={()=>scroll(clinicRail,-1)}/><div className="rh-clinic-rail" ref={clinicRail}>{facilityCards(rotated(clinics,offsets.clinics),'clinic')}</div><Arrow direction="right" label="Next clinics" onClick={()=>scroll(clinicRail,1)}/></div></section><section><SectionTitle href="/lab-tests" label="View All Tests">Popular Lab Tests in Dubai</SectionTitle><div className="rh-test-list">{[['calendar','Complete Blood Count (CBC)','120'],['medicine','Vitamin D Test','150'],['skin','Thyroid Profile','200'],['file','Diabetes Panel','170']].map(([icon,name,price],i)=><div key={name}><span className={`rh-icon rh-tone-${i}`}><Icon name={icon} size={15}/></span><strong>{name}</strong><b>AED {price}</b><button className="rh-primary" onClick={()=>sample(name,'This is a sample test and price. Browse the live test catalog for actual availability and fees.')}>Book</button></div>)}</div></section></div>
      <section className="rh-process"><h2>How It Works</h2><p>Get quality healthcare in 4 simple steps</p><div>{[['search','Search','Find doctors, hospitals, clinics','or tests'],['calendar','Book','Choose date and time',''],['video','Consult','Visit in-clinic or go online',''],['file','Get Care','Receive prescriptions, test results','and follow-up']].map(([icon,title,line,line2],i)=><article key={title}><span className="rh-step-icon"><Icon name={icon} size={29}/></span><h3>{i+1}. {title}</h3><p>{line}<br/>{line2}</p>{i<3&&<span className="rh-step-arrow">→</span>}</article>)}</div></section>
      <section className="rh-about"><article><div><h2>Who We Are &amp; What We Do</h2><h3>Your Trusted Healthcare Directory in Dubai</h3><p>MedCare is a complete healthcare platform that connects patients with trusted doctors, hospitals, clinics and labs across the UAE. We make it easy to find care, book and manage your healthcare needs — all in one place. We aim to make quality healthcare more accessible to everyone with accurate information, verified listings and a seamless booking experience.</p><Link className="rh-outline" href="/directory">Learn More About Us →</Link></div><Photo crop={[316,1133,188,132]} label="Sample family consultation"/></article><article><div><h2>Why MedCare is Helpful</h2><CheckList items={['Find trusted and verified healthcare providers','Book appointments in 1 click','Get video consultation from home','Compare services, reviews and prices','Access lab tests and health packages','Read expert health articles','Manage all your healthcare records in one place']}/></div><Photo crop={[703,1135,98,130]} label="Sample patient using a phone"/></article></section>
      <section className="rh-business"><div className="rh-business-main"><h2>List Your Business on MedCare</h2><p>Join thousands of healthcare providers and grow with us.</p><div className="rh-business-rail"><Arrow direction="left" label="Browse business types" onClick={()=>sample('Healthcare business profiles','Choose a doctor, hospital, clinic or lab account to create your actual business listing.')}/>{business.map(([icon,title,items,cta,role],i)=><article className={`rh-business-card rh-business-${i}`} key={role}><h3><span className="rh-icon"><Icon name={icon} size={22}/></span>{title}</h3><CheckList items={items}/><Link className="rh-primary" href={`/auth?mode=register&role=${role}`}>{cta} →</Link></article>)}</div></div><aside><h2>Why List with Us?</h2><CheckList items={['Reach thousands of patients in UAE','Build trust with verified profile','Manage bookings without confusion','Showcase your services, prices and offers','Get insights and analytics','Increase visibility and grow your business']}/><Link className="rh-primary" href="/list-your-business">View Listing Packages →</Link></aside></section>
      <section className="rh-platform"><h2>All-in-One Platform for Healthcare Providers</h2><div>{[['user','Profile Management','Update your details anytime'],['calendar','Appointment Management','Manage online & in-clinic bookings'],['people','Patient Management','Access patient history and records'],['star','Reviews & Ratings','Build trust with patient feedback'],['file','Blog Posts','Share articles and health tips'],['card','Analytics & Reports','Track performance and growth']].map(([icon,title,text],i)=><Link key={title} href="/dashboard"><span className={`rh-icon rh-tone-${i}`}><Icon name={icon} size={22}/></span><div><strong>{title}</strong><p>{text}</p></div></Link>)}</div></section>
      <section className="rh-articles"><SectionTitle href="/blog" label="View All Articles">Latest Health Articles</SectionTitle><div>{articles.map(([title,category,crop],i)=><button key={title} onClick={()=>sample(title,'This is a sample article card from the supplied design. Open Health Articles to read published content.')}><Photo crop={[...crop]} label={category+' article illustration'}/><div><h3>{title}</h3><p><span>{category}</span><i/> Oct {12-i*2}, 2026</p></div></button>)}</div></section>
      <section className="rh-bottom"><div className="rh-pricing"><h2>Pricing Packages for Business Listings</h2><div className="rh-plan-tabs">{['Doctor','Clinic','Hospital','Lab'].map(role=><button key={role} aria-pressed={planRole===role} className={planRole===role?'active':''} onClick={()=>setPlanRole(role)}>{role}</button>)}</div><div className="rh-plan-cards"><Arrow direction="left" label="View listing plan details" onClick={()=>sample('Sample listing plans','Basic, Professional and Premium are dummy packages shown to reproduce the supplied design. No subscription is purchased here.')}/>{[['Basic','0',['Profile listing','Contact details','Basic information'],'Get Started'],['Professional','499',['Verified badge','Appointment booking','Manage reviews','Add services & prices'],'Choose Plan'],['Premium','999',['Top search visibility','Featured listing','Analytics & reports','Priority support'],'Choose Plan']].map(([title,price,features,cta],i)=><article key={String(title)}><h3>{title}</h3><strong>AED {price}<small> / year</small></strong><CheckList items={features as string[]}/><button className={i===0?'rh-outline':'rh-primary'} onClick={()=>sample(`${title} ${planRole} plan`,'This is a sample pricing package. No subscription is activated and no payment is collected. Use the business listing page to explore the live service.')}>{cta}</button></article>)}</div></div><div className="rh-faq"><SectionTitle href="/list-your-business" label="View All FAQs">Frequently Asked Questions</SectionTitle><div>{questions.map(([question,answer])=><details key={question}><summary>{question}<span>⌄</span></summary><p>{answer}</p></details>)}</div></div><div className="rh-testimonials"><SectionTitle href="/doctors" label="View All Reviews">What Our Patients Say</SectionTitle><div className="rh-testimonial-card"><Arrow direction="left" label="Previous testimonial" onClick={()=>sample('Sample testimonial','This quotation and patient identity are dummy content from the supplied design.')}/><blockquote>“Very professional and caring doctor. The video consultation was smooth and I got my prescription within minutes.”</blockquote><span className="rh-review-stars">★ ★ ★ ★ ★</span><div><Photo crop={[654,1753,30,32]} label="Sample patient avatar"/><span><strong>Ayesha Malik</strong><small>Dubai, UAE</small></span></div><Arrow direction="right" label="Next testimonial" onClick={()=>sample('Sample testimonial','The reference contains one sample review. Actual patient reviews can be found on published provider profiles.')}/></div></div></section>
    </main>
    <section className="rh-join"><div className="rh-wrap"><div><h2>Join MedCare Today</h2><p>Whether you’re a patient or a healthcare provider, MedCare makes healthcare simpler, faster<br className="rh-desktop-break"/> and more accessible for everyone in the UAE.</p></div><Link className="rh-primary" href="/doctors">Find a Doctor →</Link><Link className="rh-white" href="/list-your-business">List Your Business →</Link></div></section>
    <div className="rh-demo-note">Design preview · dummy providers, reviews, prices and statistics</div>
    {dialog&&<div className="rh-dialog-backdrop" onClick={e=>{if(e.target===e.currentTarget)setDialog(null)}}><section className="rh-dialog" role="dialog" aria-modal="true" aria-labelledby="rh-dialog-title"><button ref={closeButton} className="rh-dialog-close" aria-label="Close preview" onClick={()=>setDialog(null)}>×</button><span className="rh-demo-label">Sample content</span><h2 id="rh-dialog-title">{dialog.title}</h2><p>{dialog.body}</p><div><button className="rh-outline" onClick={()=>setDialog(null)}>Back to preview</button><Link className="rh-primary" href="/directory">Open Live Directory →</Link></div></section></div>}
  </div>;
}
